name: CI
on:
  pull_request:
    branches: ['**']
  push:
    branches: ['**']
    tags: [v*]
jobs:
  call-workflow-build-scala:
    uses: softwaremill/github-actions-workflows/.github/workflows/build-scala.yml@main
    # run on 1) push, 2) external PRs, 3) softwaremill-ci PRs
    # do not run on internal, non-steward PRs since those will be run by push to branch
    if: |
      github.event_name == 'push' || 
      github.event.pull_request.head.repo.full_name != github.repository ||
      github.event.pull_request.user.login == 'softwaremill-ci'
    with:
      java-version: '11'
      java-opts: '-Xmx4G'
      sttp-native: 1
      install-libidn2: true

  call-workflow-mima:
    uses: softwaremill/github-actions-workflows/.github/workflows/mima.yml@main
    # run on 1) push, 2) external PRs, 3) softwaremill-ci PRs
    # do not run on internal, non-steward PRs since those will be run by push to branch
    if: |
      github.event_name == 'push' || 
      github.event.pull_request.head.repo.full_name != github.repository ||
      github.event.pull_request.user.login == 'softwaremill-ci'
    with:
      java-version: '11'
      java-opts: "-Xmx4G"

  call-workflow-publish-release:
    uses: softwaremill/github-actions-workflows/.github/workflows/publish-release.yml@main
    needs: [call-workflow-build-scala]
    if: github.event_name != 'pull_request' && (startsWith(github.ref, 'refs/tags/v'))
    secrets: inherit
    with:
      java-version: '11'
      java-opts: "-Xmx4G"
      sttp-native: 1

  call-workflow-label:
    # only for PRs by softwaremill-ci
    if: github.event.pull_request.user.login == 'softwaremill-ci'
    uses: softwaremill/github-actions-workflows/.github/workflows/label.yml@main

  call-workflow-auto-merge:
    # only for PRs by softwaremill-ci
    if: github.event.pull_request.user.login == 'softwaremill-ci'
    needs: [ call-workflow-build-scala, call-workflow-mima, call-workflow-label ]
    uses: softwaremill/github-actions-workflows/.github/workflows/auto-merge.yml@main